version: "3"

services:
  my-jekyll-container:
    image: my-ruby-env:latest # Replace with the actual image name
    container_name: local_jekyll
    restart: always
    tty: true
    volumes:
      - ./app:/app
      - ./conf:/etc/nginx/conf.d
    ports:
      - "80:80"
networks:
  my-network:
    driver: bridge
